# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf611ddd00df44d815b81d381939570695d48457ed722ccff886085b0e7124db4102713394c8e6e5f7e6f20b17bdfaeb90c79532974bf7035abfe7a8172a20ec

test:
  secret_key_base: 1d042480c2f5394ebbf194d36ecb3bc6bbf81628f9ebc4656df575c14592227aa968f9061f8fba573a8e9f30adb4a872dd77bc7f4309772216576baec6c2319b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
